### ISSUE TITLE
dnscrypt2 and forkplayer = 404 error

### ISSUE THREAD

**Issue by uzazzap** [blackcofee/guides#2]
Hi!
When im configured dnscrypt (works fine) and forkplayer dns replace with mac addr of my TV, my forkplayer return 404 error and never start.
404 cause dnscrypt? Can i configure exception for my tv?

**Comment by blackcofee** [comment]
Hi. 
You must delete the entry in `/etc/storage/post_iptables_script.sh`
```
### Redirect DNS
iptables -t nat -I PREROUTING -i br0 -p udp --dport 53 -j DNAT --to $(nvram get lan_ipaddr)
iptables -t nat -I PREROUTING -i br0 -p tcp --dport 53 -j DNAT --to $(nvram get lan_ipaddr)
```
